### PR TITLE
Add Pseudo Jaffe profiles

### PR DESCRIPTION
**Pull request by aymgal**
This PR adds support for `'PJAFFE'` and `'PJAFFE_ELLIPSE'` to jaxtronomy, based on their original implementation in lenstronomy.

A few things that may require discussion before merging:
- test routines for profiles: do we only have tests against the original lenstronomy profiles, or do we also keep hard-coded numerical tests? (e.g. see current `test_p_jaffe.py`
- inverting variables (`Ra` and `Rs`) is not JAX-friendly since derivatives cannot be tracked properly. A simple workaround is that the modeler place appropriate priors on these two parameters, which do not overlap.
- probably not all lenstronomy submodules will need to be moved to JAXtronomy. For instance, the `LensProfileBase` class and utilities to create grids do not need to rely on JAX (as they do not deal with optimizable parameters), so one can just import the original lenstronomy submodules.

### CODE REVIEW

**Comment by sibirrer** [comment]
Thank you very much @aymgal! The test only fails because of the mismatch of the version of lenstronomy. I hope this does not cause troubles.

**Comment by aymgal** [comment]
@sibirrer Is there actually a need for this test? If yes, I can simply update it, but it might be better to have a requirements.txt instead.

**Comment by sibirrer** [comment]
> @sibirrer Is there actually a need for this test? If yes, I can simply update it, but it might be better to have a requirements.txt instead.

ah, there might not even be a need for this since we are using the pip version. So we can also remove this test

**Comment by aymgal** [comment]
@sibirrer I added requirements.txt and updated the setup.py. I bumped the required lenstronomy version to a most recent 1.11.0, and followed lenstronomy for scipy and numpy.
Please let me know what you think above my above points! Then I will finalize the PR.

**Comment by aymgal** [comment]
It seems there are problems related to `numba.jit` from the lenstronomy part, but I don't know `numba` enough to solve them...

**Comment by sibirrer** [comment]
> It seems there are problems related to `numba.jit` from the lenstronomy part, but I don't know `numba` enough to solve them...

hmm, I think we have to replace/re-code all the bits that were using numba. I am not too surprised that numba and jax are not compatible with each other

**Comment by aymgal** [comment]
@sibirrer Let's see if this works: I propose to have a specific config.yaml for the unit tests, which disable `numba`. I modified the CI pipeline to copy the custom config.yaml to `~/.config/lenstronomy` (hard to test on my laptop as I don't have the same setup as for github actions).

**Comment by sibirrer** [comment]
hmm, @aymgal seems the config file was not recognized. Perhaps you can simulate the full CI locally with 'tox'? That should create a virtual environment on the fly to minique as good as possible the CI

**Comment by aymgal** [comment]
@sibirrer Not sure why lenstronomy was not detecting the user config.yaml (even though it was correctly created). I also got the issue with tox.
So now I tried with `export NUMBA_DISABLE_JIT=false`, which passed using tox.

**Comment by aymgal** [comment]
Ok it's finally working. I will simply increase the coverage of the profile and we should be good.

**Comment by sibirrer** [comment]
wohoo!!! Thank you very much @aymgal! Please ping me when you are ready and then happy to merge (you can ignore the pre-commit.ci for now since that should be fixed with @ajshajib 's PR

**Comment by aymgal** [comment]
All good for me! @sibirrer

**Review by sibirrer — APPROVED** [review]
Thank you very much @aymgal !

**Pull request merged**
